// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ydcpplplnndourqawcna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlkY3BwbHBsbm5kb3VycWF3Y25hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMTUyMDIsImV4cCI6MjA2MDU5MTIwMn0.dVUmHPSVnLb-1F6F3A2OqMtxsKrQMRp1a_6O49eASaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);